name: wallet

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant Permissions to gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build
  test:
    needs: build
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant Permissions to gradlew
        run: chmod +x gradlew
      - name: Test
        run: ./gradlew test --tests "*"
  deploy:
    needs:  [build, test]
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Wait for Render Deployment
        uses:  johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-cgrdujrk9u56e3m46gug
          api-key: JV5Z-gXgIoY
